name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Rodar testes Maven
        run: mvn test

      - name: Build do projeto (jar)
        run: mvn clean package -DskipTests

      - name: Build imagem Docker
        run: docker build -t delivery-tech:latest .

      - name: Rodar container para testes de integração
        run: docker run -d --name delivery-tech-test -p 8080:8080 delivery-tech:latest

      - name: Esperar aplicação subir
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep UP; then
              echo "App está no ar!";
              exit 0;
            fi
            sleep 2
          done
          echo "App não subiu!" && exit 1

      - name: Testar endpoint principal
        run: curl -f http://localhost:8080/actuator/health

      - name: Parar container de teste
        run: docker stop delivery-tech-test

      - name: Salvar logs do pipeline
        run: |
          mkdir -p entregaveis
          if [ -d target/surefire-reports ]; then
            cp -r target/surefire-reports entregaveis/
          else
            echo "Nenhum relatório de teste encontrado." > entregaveis/sem-relatorio.txt
          fi

      - name: Upload dos logs como artefato
        uses: actions/upload-artifact@v4
        with:
          name: logs-pipeline
          path: entregaveis/

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular deploy em homologação
        run: echo "Deploy realizado em ambiente de homologação (simulado)"

      - name: Criar relatório do pipeline
        run: |
          mkdir -p entregaveis
          echo "# Relatório do Pipeline" > entregaveis/relatorio.md
          echo "## Etapas executadas:" >> entregaveis/relatorio.md
          echo "- Testes automatizados" >> entregaveis/relatorio.md
          echo "- Build do projeto e Docker" >> entregaveis/relatorio.md
          echo "- Deploy em homologação (simulado)" >> entregaveis/relatorio.md
          echo "- Logs salvos em entregaveis/" >> entregaveis/relatorio.md

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-pipeline
          path: entregaveis/relatorio.md